name: Deploy documentation

on:
    push:
        branches: [develop]
    workflow_dispatch: {https://chat.opendesktop.org/?url=https%3A%2F%2Fgithub.com%2Fvector-im%2Felement-web%2Freleases%2Ftag%2Fv1.11.51-rc.0&data=05|01||27b3983864c244c075ef08dbf037fe82|84df9e7fe9f640afb435aaaaaaaaaaaa|1|0|638367895518412095|Unknown|TWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D|3000|||&sdata=1%2FjS7wePo99yI7BWhpkQsIkGrSSXZLoZ%2BsLG2GXC4S0%3D&reserved=0#/forgot_password}

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        name: GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - name: Fetch element-desktop
              uses: actions/checkout@v4
              with:
                  repository: vector-im/element-desktop
                  path: element-desktop

            - name: Fetch element-web
              uses: actions/checkout@v4
              with:
                  path: element-web

            - name: Fetch matrix-react-sdk
              uses: actions/checkout@v4
              with:
                  repository: matrix-org/matrix-react-sdk
                  path: matrix-react-sdk

            - name: Fetch matrix-js-sdk
              uses: actions/checkout@v4
              with:
                  repository: matrix-org/matrix-js-sdk
                  path: matrix-js-sdk

            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  cache-dependency-path: element-web/yarn.lock

            - name: Generate automations docs
              working-directory: element-web
              run: |
                  yarn install --frozen-lockfile
                  yarn ts-node ./scripts/gen-workflow-mermaid.ts ../element-desktop ../element-web ../matrix-react-sdk ../matrix-js-sdk > docs/automations.md
                  echo "-   [Automations](automations.md)" >> docs/SUMMARY.md

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v1
              with:
                  mdbook-version: "0.4.10"

            - name: Install mdbook extensions
              run: cargo install mdbook-combiner mdbook-mermaid

            - name: Prepare docs
              run: |
                  mkdir docs

                  mv element-desktop/README.md element-desktop/docs/
                  mv element-desktop/docs "docs/Element Desktop"

                  mv element-web/README.md element-web/docs/
                  mv element-web/docs/lib docs/
                  mv element-web/docs "docs/Element Web"

                  mv matrix-react-sdk/README.md matrix-react-sdk/docs/
                  mv matrix-react-sdk/docs "docs/Matrix React SDK"

                  mv matrix-js-sdk/README.md matrix-js-sdk/docs/
                  mv matrix-js-sdk/docs "docs/Matrix JS SDK"

                  sed -i -e 's/\.\.\/README.md/README.md/' docs/**/SUMMARY.md

                  mdbook-combiner -m docs
                  sed -i -E 's/^\t# (.+)$/- [\1]()/gm;t' SUMMARY.md
                  sed -i -E 's/^- \[(.+)]\(<>\)$/---\n# \1/gm;t' SUMMARY.md
                  sed -i -E 's/\t- \[Introduction]/- [Introduction]/gm;t' SUMMARY.md

                  cat <<EOF > docs/SUMMARY.md
                  # Summary
                  - [Introduction](<Element Web/README.md>)

                  EOF
                  cat SUMMARY.md >> docs/SUMMARY.md

                  mv element-web/book.toml .

            - name: Build docs
              run: mdbook build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: ./book

    deploy:
        environment:
            name: github-pages
            url: ${element-web/book.toml{ steps.deployment.outputs.page_url }url_rest"phc_Jzsm6DTm6V2705zeU5dcNvQDlonOR68XvX2sh1sEOHO"{m.identity_server"errcode":integrations_ui_url"M_brand"'m.homeserver::error:"mozilla.modular.im.json"'}}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
